-- MySQL Script generated by MySQL Workbench
-- Thu Feb 11 17:57:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chatbox_dbb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatbox_dbb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatbox_dbb` DEFAULT CHARACTER SET utf8 ;
USE `chatbox_dbb` ;

-- -----------------------------------------------------
-- Table `chatbox_dbb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbox_dbb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(85) NULL,
  `password` VARCHAR(85) NULL,
  `email` VARCHAR(85) NULL,
  `profile_img` BLOB(300000) NULL,
  `recent_connexion` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbox_dbb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbox_dbb`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_messages_user_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_messages_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `chatbox_dbb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
