-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 06:21:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pulserch_
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pulserch_
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pulserch_` DEFAULT CHARACTER SET utf8 ;
USE `pulserch_` ;

-- -----------------------------------------------------
-- Table `pulserch_`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pulserch_`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(85) NULL,
  `password` VARCHAR(85) NULL,
  `email` VARCHAR(85) NULL,
  `profile_img` BLOB(300000) NULL,
  `recent_connexion` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulserch_`.`user_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pulserch_`.`user_has_user` (
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  PRIMARY KEY (`sender_id`, `receiver_id`),
  INDEX `fk_user_has_user_user1_idx` (`receiver_id` ASC),
  INDEX `fk_user_has_user_user_idx` (`sender_id` ASC),
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`sender_id`)
    REFERENCES `pulserch_`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `pulserch_`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulserch_`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pulserch_`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NULL,
  `user_has_user_sender_id` INT NOT NULL,
  `user_has_user_receiver_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_has_user_sender_id`, `user_has_user_receiver_id`),
  INDEX `fk_messages_user_has_user1_idx` (`user_has_user_sender_id` ASC, `user_has_user_receiver_id` ASC),
  CONSTRAINT `fk_messages_user_has_user1`
    FOREIGN KEY (`user_has_user_sender_id` , `user_has_user_receiver_id`)
    REFERENCES `pulserch_`.`user_has_user` (`sender_id` , `receiver_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
